version: "2.24"
name: pdu_poll

services:
  influxdb:
    image: influxdb:latest
    networks:
      - frontend
      - backend
    ports:
      - 8086:8086
    volumes:
      - db-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=/run/secrets/INFLUX_ADMIN_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=testPassword
      - DOCKER_INFLUXDB_INIT_ORG=byu
      - DOCKER_INFLUXDB_INIT_BUCKET=pdu-data
      - DOCKER_INFLUXDB_INIT_RETENTION=90d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=G_WAOJWZ1ymjZLUn9L1ZsrpKxYIsUYk42g7AARJgc3CdIT5GEdzLOn9gdT2MYVvIL1k46o_4QV3OQ9KgfP3txQ==
    secrets:
      - INFLUX_ADMIN_USERNAME
  poller:
    image: ubuntu:latest
    networks:
      - backend
    command: bash -c "apt-get update && apt-get install curl -y && curl -o /root/setup.sh https://raw.githubusercontent.com/RJ-246/byu-dc-pdupoller/main/setup.sh && bash ./root/setup.sh && tail -f /dev/null"
  grafana:
    image: grafana/grafana-oss:latest
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
  grafana-data:
  poll-data:

secrets:
  INFLUX_ADMIN_USERNAME:
    environment: "ADMIN_USERNAME"
