name: pdu_poll

services:
  influxdb:
    image: influxdb:latest
    networks:
      - frontend
      - backend
    ports:
      - 8086
    volumes:
      - db-data:/var/lib/influxdb2
  poller:
    image: ubuntu:latest
    networks:
      - backend
  grafana:
    image: grafana:latest
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
  grafana-data:
  poll-data:
