name: pdu_poll

services:
  poller:
    depends_on:
      flask:
        condition: service_healthy
    build: ./docker/poller
    networks:
      - backend

  grafana:
    image: grafana/grafana-oss:latest
    networks:
      #- frontend
      - backend
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    networks:
      - backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "strongPassword"
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend
    healthcheck:
      test: 'echo ''db.runCommand("ping").ok'' | mongosh --quiet'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  flask:
    depends_on:
      mongodb:
        condition: service_healthy
    build: ./docker/flask
    networks:
      - backend
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  #frontend:
  #driver: bridge
  backend:
    driver: bridge

volumes:
  grafana-data:
  poll-data:
  prometheus-data:
  mongodb-data:
