version: "2.24"
name: pdu_poll

services:
  influxdb:
    image: influxdb:latest
    networks:
      - frontend
      - backend
    ports:
      - 8086:8086
    volumes:
      - db-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$ADMIN_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$ADMIN_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$INFLUX_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$INFLUX_BUCKET
      - DOCKER_INFLUXDB_INIT_RETENTION=$INFLUX_RETENTION
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$ADMIN_TOKEN
  poller:
    image: ubuntu:latest
    networks:
      - backend
    command: bash -c "apt-get update && apt-get install curl -y && curl -o /root/setup.sh https://raw.githubusercontent.com/RJ-246/byu-dc-pdupoller/main/setup.sh && bash ./root/setup.sh && tail -f /dev/null"
    volumes:
      - poll-data:/root
    environment:
      - INFLUX_TOKEN=$ADMIN_TOKEN
  grafana:
    image: grafana/grafana-oss:latest
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
  grafana-data:
  poll-data:
