name: pdu_poll

services:
  poller:
    build: ./docker/poller
    networks:
      - backend

  grafana:
    image: grafana/grafana-oss:latest
    networks:
      #- frontend
      - backend
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    networks:
      - backend
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "strongPassword"
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  # flask:
  #   image:

networks:
  #frontend:
  #driver: bridge
  backend:
    driver: bridge

volumes:
  grafana-data:
  poll-data:
  prometheus-data:
  mongodb-data:
