version: "2.24"
name: pdu_poll

services:
  influxdb:
    image: influxdb:latest
    networks:
      - frontend
      - backend
    ports:
      - 8086:8086
    volumes:
      - db-data:/var/lib/influxdb2
  poller:
    image: ubuntu:latest
    networks:
      - backend
    command: bash -c "apt-get update && apt-get install curl && curl -o /root/setup.sh tail -f /dev/null"
  grafana:
    image: grafana/grafana-oss:latest
    networks:
      - frontend
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
  grafana-data:
  poll-data:
